### ISSUE TITLE
🐞 Trace View / Timeline doesn't scroll to span when clicking on a specific span 

### ISSUE THREAD

**Issue by BaruchReut** [teletrace/teletrace#1007]
## Describe the Bug
In Trace View when clicking on a specific span the timeline doesn't scroll to the specific span

## Steps To Reproduce

1. Go to Trace View
2. Click on a specific span that is not visible on the current size of the timeline
4. Timeline doesn't scroll to the specific span

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/89512916/211566753-e44528d2-d081-49fa-966c-358c56cbadfc.png">

## Expected Behavior
On clicking on a span that is not visible on the current timeline size - it should be scrolled to the span in the timeline

## Tasks
- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: laptop
- Browser: safari
- OS: iOS

**Comment by haimrait** [comment]
Does not reproduce
