### ISSUE TITLE
🐞 Trace View / Deselect graph node won't effect only until hover

### ISSUE THREAD

**Issue by itaykat** [teletrace/teletrace#1098]
Cc:

Hi

## Describe the Bug

Deselect graph node won't effect only until hover the specific selected node

## Steps To Reproduce

1. click node
2. click blank space in canvas

## Expected Behavior

deselect node

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment
- Browser: Safari
- OS: iOS

## Screenshots

[
](https://user-images.githubusercontent.com/67950726/211579915-f73e90c0-79a3-4cb7-a67d-8b44c9e17477.mov)

**Comment by haimrait** [comment]
Does not reproduce
