### ISSUE TITLE
🐞Trace view / some content is selected during resizing 

### ISSUE THREAD

**Issue by nirf-cisco** [teletrace/teletrace#1102]
Cc:

Hi

## Steps To Reproduce

1. Open trace view
2. move the slider 

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]

https://user-images.githubusercontent.com/92082083/211581370-0ffd6914-2efb-4c8f-8a57-5f4e10b78dcb.mov

- Deployment tool: [e.g., helm]
- Browser: safari
- DB: SQLite

**Comment by haimrait** [comment]
Does not reproduce
