### ISSUE TITLE
🐞 The scroll bar should start after the table headline

### ISSUE THREAD

**Issue by sagivr2020** [teletrace/teletrace#1111]
Cc: @razlo @haimrait 

Hi

When scrolling the table, the scroll bar starts from the top right of the table and not after the table headline

## Steps To Reproduce

1. Scroll down the table
2. view the scroll bar (from where it begins to scroll)

## Expected Behavior
The scroll bar should start after the table headline

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: laptop
- Deployment tool: elastic/sqlite
- Browser: firefox
- OS: ios

**Comment by haimrait** [comment]
Does not reproduce
