### ISSUE TITLE
🐞 Empty value for parent span id

### ISSUE THREAD

**Issue by sagivr2020** [teletrace/teletrace#1119]
Cc: @razlo @haimrait 

Hi

## Describe the Bug

When filtering by parent span id it shows an empty option.

## Steps To Reproduce

1. Filter by parent span id
2. Open the values
3. empty value will appear

## Expected Behavior

should add a concrete value for parent span id

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: laptop
- Deployment tool: elastic, sqllite
- Browser: firefox
- OS: iOS

## Screenshots
<img width="1824" alt="image" src="https://user-images.githubusercontent.com/72692043/211585281-0c6edc8e-ef44-4ce3-a56f-37c6b811d5c6.png">

**Comment by feinblat** [comment]
Solved in #1254
