### ISSUE TITLE
🐞 Trace graph is not responsive

### ISSUE THREAD

**Issue by ophiryael** [teletrace/teletrace#1121]
The trace graph does not react to window size changes.
1. Enter the trace graph.
2. Resize the browser window.
3. The trace graph gets hidden (picture attached).
![Screenshot 2023-01-10 at 17 03 55](https://user-images.githubusercontent.com/37577482/211586537-cea95fb0-bc9f-4dee-a3a1-eda3c8459d66.png)

The trace graph should "reflow" on window size change.
Click on the "fit view" button in the trace graph controls to achieve the desired effect (which should happen automatically):
![Screenshot 2023-01-10 at 17 04 35](https://user-images.githubusercontent.com/37577482/211587007-e0f3a824-2402-4fc0-9e15-ad4985da125d.png)

**Comment by haimrait** [comment]
As Itay Katz said it will not fix because it is the expected behavior
