### ISSUE TITLE
🐞 Trace View / Y scrollbar of the timeline view hides data

### ISSUE THREAD

**Issue by ranrib** [teletrace/teletrace#1135]
## Describe the Bug

When getting into a trace that the timeline part has a scrollbar, it scrolls the entire component rather than just the list of spans. If a user scrolls down, some data/functionality hides from the screen, like duration or resetting the zoom.

before:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/24767098/211772315-5bcdbeed-2e76-4780-92b4-b6fa926bd0db.png">

after:
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/24767098/211772014-000ebcda-8f2c-4cda-96a9-3d3cd5d2bf2e.png">

## Steps To Reproduce

Go to a trace with many spans and scroll the timeline view to the bottom

## Expected Behavior

Only the spans list should be scrolled, while the top header of the timeline should remain "sticked"

**Comment by haimrait** [comment]
Fixed and does not reproduce
