### ISSUE TITLE
🐞 Value selector in custom filter not showing selected values

### ISSUE THREAD

**Issue by shaqued** [teletrace/teletrace#1174]
Cc:

Hi

once selecting a value it is removed from the dropdown

## Expected Behavior

all selected values will remain in the dropdown

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm]
- Browser: [e.g. chrome, safari]

**Comment by haimrait** [comment]
Does not reproduce
