### ISSUE TITLE
🐞 Editing a filter to a combination of a key + operator of an existing filter results in undefined behaviour

### ISSUE THREAD

**Issue by galbash** [teletrace/teletrace#1266]
Cc: @tvaintrob @nirf-cisco @shaqued @Madina-Mamysheva 

Hi @OfirD55 

## Describe the Bug
When I edit a filter and set the operator in a way that the tag + operator combination is the same as another existing filter, I get two filters with the same tag + operator combo. This results in undefined behavior (since we identify a chip by a tag + operator combo) and may lead to the delete button to malfunction and the sidebar to be out of sync.

## Steps To Reproduce

1. Go to Spans search
2. add a filter spans.status.code in Error
3. add a filter spans.status.code not in Unset
4. change the second filter to 'in Unset'

## Expected Behavior
@OfirD55 We need to decide if we want the second filter to be dropped and the first one overriden, or to allow two chips with the same tag key and operator.

## Screenshots
![image](https://user-images.githubusercontent.com/6430006/213916896-0a8eaf97-cd84-44ea-b94d-d6eaa6cf3f6b.png)

**Comment by shaqued** [comment]
@haimrait I have a PR to override pre-existing filter with the same key + operator
