### ISSUE TITLE
✨ Design Backend API for Histogram Aggregations

### ISSUE THREAD

**Issue by Tavh** [teletrace/teletrace#1592]
Design a backend API that allows different kinds of histogram aggregations.

- Implemented in an abstract way that potentially fits different kinds of databases
- Allow different types of intervals (startTime, duration, etc...)

**Comment by haimrait** [comment]
Hey @Tavh can you please add more description for this issue?

**Comment by Tavh** [comment]
@haimrait yea i'm working out an example api

**Comment by Tavh** [comment]
Current proposed API:

Histogram
-----------------
Description:
  Returns a histogram based on the specified time frame, filters, interval and aggregationss spec.

Request:
  POST /v1/histogram
  {
    "timeframe": "string (e.g., 'last_15_minutes', 'last_1_hour', etc.)",
    "filters": "array of filter objects",
    "sort": "string (e.g., 'desc', 'asc')",
    "interval": "integer (e.g., 600000)",
    "intervalKey": "string (e.g., 'span.startTimeUnixNano')",
    "label": "string (e.g., 'errors_histogram')",
    "aggregations": [
      {
        "func": "enum ( 'COUNT', 'PERCENTILES')",
        "label": "string (e.g., 'errors_count')",
        "groupBy": "string (e.g., 'span.attributes.http.status_code')"
        "maxGroups": "integer (e.g., 5)",
        "key": "string (e.g, "span.id")
      }
    ]
  }


POST /v1/histogram

errors example:
```
{
    "timeframe": ...
    "filters": ...
    "sort": ...
    "interval": 600000,
    "intervalKey": "span.startTimeUnixNano",
    "label": "errors_histogram",
    "aggregations": [
        {
            "func": "COUNT",
            "label": "errors_count",
            "groupBy": "span.attributes.http.status_code"
        }
    ]
}
```

latency example
```
{
    "timeframe": ...
    "filters": ...
    "sort": ...
    "interval": 600000,
    "intervalKey": "span.startTimeUnixNano",
    "label": "latency_histogram",
    "aggregations": [
        {
            "func": "PERCENTILES",
            "label": "latency_percentiles",
            "key": "externalFields.durationNano"
        }
    ]
}
```

requests example
```
{
    "timeframe": ...
     "filters": [
        {
            "keyValueFilter": {
                "key": "span.kind",
                "operator":"in",
                "value": "Client"
            }
        }
    ],
    "sort": ...
    "interval": 600000,
    "intervalKey": "span.startTimeUnixNano",
    "label": "requests_histogram",
    "aggregations": [
        {
            "func": "COUNT",
            "label": "requests_count"
        }
    ]
}
```


@roybh1 @tvaintrob @tglanz 
What do you think?

**Comment by tglanz** [comment]
Can the frontend potentially make a single request?

**Comment by Tavh** [comment]
@roybh1 yes, you can use a different interval

**Comment by Tavh** [comment]
> Can the frontend potentially make a single request?
> 
> ```
> {
>     "timeframe": ...
>      "filters": [
>         {
>             "keyValueFilter": {
>                 "key": "span.kind",
>                 "operator":"in",
>                 "value": "Client"
>             }
>         }
>     ],
>     "sort": ...
>     "interval": 600000,
>     "intervalKey": "span.startTimeUnixNano",
>     "label": "requests_histogram",
>     "aggregations": {
>           "requests_count": {
>                  "func": "COUNT",
>             } ,
>             "latency_percentiles": {
>                  "func": "COUNT",
>                  "key": "externalFields.durationNano"
>             },
>             "errors_count": {
>                  "func": "COUNT",
>                  "groupBy": "span.attributes.http.status_code"
>             } 
>         }
>     }
> }
> ```

Should work fine

**Comment by Tavh** [comment]
@haimrait 

I think we have an agreement on the API so I'm moving on to implementation
