### ISSUE TITLE
📝 How to implement this on a Django application.

### ISSUE THREAD

**Issue by jonnydefijn** [teletrace/teletrace#1593]
## Pain

Unclear on how to implement this on a Django application./

## Suggested Documentation

A section describing how to implement this on a Django application.

Thanks!

**Comment by ophiryael** [comment]
Hi @jonnydefijn, thanks for taking an interest in the project.
Instructions on instrumenting a Django application can be found in the official OpenTelemetry Python SDK library docs.
https://opentelemetry-python.readthedocs.io/en/latest/examples/django/README.html

**Comment by tvaintrob** [comment]
Hi @jonnydefijn , did @ophiryael's comment help you figure out the way to work with django? if so I would like to close this issue, if you need further assistance feel free to comment bellow or reach me over slack (link is in the [README](https://github.com/teletrace/teletrace#:~:text=20%20hours%20ago-,README.md,-%F0%9F%93%9D)
