### ISSUE TITLE
📝 Demo application repo link is wrong

### ISSUE THREAD

**Issue by jonnydefijn** [teletrace/teletrace#1594]
## Pain

Documentation to run demo application does not work

## Suggested Documentation

Fix the documentation

## More Information

Link to docs page:

https://docs.teletrace.io/user-guide/open_telemetry_demo/

```shell
git clone https://github.com/opentelemetry/opentelemetry-demo.git

Cloning into 'opentelemetry-demo'...
remote: Repository not found.
fatal: repository 'https://github.com/opentelemetry/opentelemetry-demo.git/' not found
```

Thanks!

**Comment by ophiryael** [comment]
Hi @jonnydefijn, this is indeed a bug. Thank you for pointing this out.
I've opened a PR to fix this issue.
