### ISSUE TITLE
Track test coverage for go components

### ISSUE THREAD

**Issue by galbash** [teletrace/teletrace#245]
**Is your feature request related to a problem? Please describe.**

As a maintainer, it's hard to keep track of what system components are tested and to what degree. While not perfect, adding coverage report and enforcement increases the chance of components having basic functionality tests

**Describe the solution you'd like**

Test coverage should be reported as part of the CI, and a minimum % should be enforced

@tvaintrob @maorlx @haimrait is this something you'd want to add now?

**Comment by haimrait** [comment]
Duplicate done in different pr
