### ISSUE TITLE
Run plugin tests in CI

### ISSUE THREAD

**Issue by roybh1** [teletrace/teletrace#251]
**Is your feature request related to a problem? Please describe.**

Currently plugins are not being tested. the existing SpanStorage ES plugin has almost no unit tests also, as its mostly interacting with an existing package. most of the plugins tests require a running instance of elasticsearch.

**Describe the solution you'd like**

Provide the guidelines for testing such tests for new plugins.
Use a script to run the required containers.
Add instructions to the contrib.md file and the plugin readme. 

in the ES SpanStorage case, write plugin tests, create a script to run elasticsearch container and run the tests in the CI.

**Comment by haimrait** [comment]
Fixed in previous prs
