### ISSUE TITLE
Move Span fields to top-level on InternalSpan

### ISSUE THREAD

**Issue by ronyis** [teletrace/teletrace#428]
Currently, in [InternalSpan](https://github.com/epsagon/lupa/blob/main/model/internalspan/v1/internal_span.go#L59) the span fields are set under `span` map (which adds a `span.` prefix, e.g. `span.name`, `span.spanID` etc.)

This adds an unnecessary burden - since the object represents a span, these tags could just be on the top level.
It will also be easier to work with such representation on the API and the UI, for example `name` instead of `span.name` and `attributes.http.host` instead of `span.attributes.http.host`.

Note - `IngestionTimeUnixNano` should probably be changed to suggest that it's a metadata field, and not a top-level span field.

**Comment by haimrait** [comment]
Decided not to continue with this issue
