### ISSUE TITLE
📚️ Span Search / Duration Slider

### ISSUE THREAD

**Issue by OfirD55** [teletrace/teletrace#765]
## Problem

Selecting a span-duration time range it’s hard and time-wasting with the current sorting options and it’s a common practice when troubleshooting latency-related issues

## Audience

All users solving a latency-related issue using the Span Search

## Proposed Work

Using a “slider” to help users pick a span-duration time range

## Presentation

1. Problem: A user wants to filter by span-duration time-range to troubleshoot a latency-related issue, but it’s hard to select a “between” value using current sorting/filtering methods. 
2. Solution:
    1. User navigates to Span Search
    2. User uses current filtering capabilities to get the relevant span dataset of the HTTP server
    3. User filters duration using the Duration Slider, setting a time range to find the recent lengthy requests 
    4. User navigates to a trace and find root-cause for high latency

![image](https://user-images.githubusercontent.com/55341028/207022905-5fdd6858-d32d-4115-a664-7d9d958f2f94.png)

   
## Interactions

- Slider should be in the Sidebar filters section
- Slider should be logarithmic because the value potentially will have a large distribution
- Slider should be dynamic
    - Meaning min/max value in slider should be min/max span-duration in current span dataset.
- Slider should filter all the relevant places on page (table, sidebar tag frequency, add chip, future charts, etc.)

## Notes from Grooming 
        

- If the user didn’t make any changes to the slider, the min/max will update according to new data coming in (both when LIVE MODE ON/when a user changes the time-range)
- If the user applied a filter using the slider, the scale of the selector will be adjusted proportionally according to the mix/max 
- We need to support greater than and below than in sync with custom filters
- We don’t want to support “between” operator for now. 
- For now its fine but I think the best would be to have the between option. We would do usability testing and see if it sounds good.
   - Need to indicate an error when ranges that don’t makes sense are chosen
        - for example ≥ 200 ms and ≤ 100 ms
            - Madina Mamysheva if the user chooses a value/range which does not exists, we provide an error message once the user clicks.

## Tasks

- [ ] Frontend implementation for duration slider
- [ ] Backend implementation for duration slider

**Comment by haimrait** [comment]
Fixed in #1302
