### ISSUE TITLE
🐞 Span Search: can't filter using side bar's "service Name"

### ISSUE THREAD

**Issue by BaruchReut** [teletrace/teletrace#945]
Hi

## Describe the Bug
On span search page, on the side bar under "Service Name" I'm searching for a service that exists in the system but gets no results.

## Steps To Reproduce
I created a test that loads 4 services, the root service contains 2 spans - parent and child, and the other 3 services contains 1 span and are connected to the root span.
![image](https://user-images.githubusercontent.com/89512916/211201027-662b545a-9bf5-4304-9dba-e453fab11f2d.png)

1. Go to search span page, side bar, "Service Name"
2. Look for the name of the loaded services
3. No service was found

![image](https://user-images.githubusercontent.com/89512916/211201211-4ce603b7-7e3b-449e-b236-424fa8298833.png)

## Expected Behavior
I would expect to see all 4 services

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Deployment tool: used the demo docker
- Browser:  chrome
- OS: iOS

**Comment by haimrait** [comment]
Does not reproduce
