### ISSUE TITLE
🐞 Span Search: can't find span using filters

### ISSUE THREAD

**Issue by BaruchReut** [teletrace/teletrace#947]
Hi

## Describe the Bug
On span search page,  I'm searching for a span that exists in the system using the filter options but gets no results.

## Steps To Reproduce
I created a test that loads 4 services, the root service contains 2 spans - parent and child, and the other 3 services contains 1 span and are connected to the root span.
![image](https://user-images.githubusercontent.com/89512916/211201552-ac79697d-16d1-421b-8350-26b0734fde47.png)

1. Go to search span page, add filters
2. key: span.spanId
3. operator: in
4. value: _enter a span that was loaded_
5. No span was found

![image](https://user-images.githubusercontent.com/89512916/211201610-6fd21186-aa79-42a4-aab3-9e1529d95da8.png)

## Expected Behavior
I would expect to see the span

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Deployment tool: used the demo docker
- Browser:  chrome
- OS: iOS

**Comment by haimrait** [comment]
Does not reproduce
