### ISSUE TITLE
🐞 Trace View / Inconsistent Span label behavior

### ISSUE THREAD

**Issue by itaykat** [teletrace/teletrace#997]
Cc:

Hi

## Describe the Bug

While hovering over the span title - the label behaves as expected (shown fully with background)
<img width="450" alt="Screenshot 2023-01-10 at 15 37 38" src="https://user-images.githubusercontent.com/67950726/211566441-5a54d8ab-f14d-4720-84a4-dac687ce3755.png">

## Expected Behavior

While hovering over the span arrow (left side) - the label is transparent 
<img width="455" alt="Screenshot 2023-01-10 at 15 37 43" src="https://user-images.githubusercontent.com/67950726/211566452-1448c8af-7b46-4595-ae85-b74da906f712.png">

Trace for example: https://app.elastic.lupaproject.io/trace/74a3b8395a7d4275da2cb9e95e8005bd?spanId=71baf1bf6df190f7

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Browser: Safari
- OS: iOS

**Comment by haimrait** [comment]
Does not reproduce
